kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: {{ .CLUSTER_NAME }}
nodes:
  - role: control-plane
  - role: worker
    kubeadmConfigPatches:
      - |
        kind: JoinConfiguration
        nodeRegistration:
          kubeletExtraArgs:
            node-labels: "test-branch={{ .CURRENT }}"
  - role: worker
    kubeadmConfigPatches:
      - |
        kind: JoinConfiguration
        nodeRegistration:
          kubeletExtraArgs:
            node-labels: "test-branch={{ .REF }}"