apiVersion: v1
kind: ConfigMap
metadata:
  name: default
data:
  FUSE_QUERY_MYSQL_HANDLER_HOST: "0.0.0.0"
  FUSE_QUERY_CLICKHOUSE_HANDLER_HOST: "0.0.0.0"
  FUSE_QUERY_HTTP_API_ADDRESS: "0.0.0.0:8081"
  FUSE_QUERY_METRIC_API_ADDRESS: "0.0.0.0:7071"
  FUSE_QUERY_FLIGHT_API_ADDRESS: "0.0.0.0:9091"
  FUSE_QUERY_MYSQL_HANDLER_PORT: "3307"
  FUSE_QUERY_CLICKHOUSE_HANDLER_PORT: "9001"